image: node:23-alpine3.20

services:
  - docker:dind

variables:
  # Defined variable can be used in case of a job failed
  # If a job failed we set the corresponding variable to true, so we can know which stage we notify about to the developer
  JOB_NAME: "default_value"
  JOB_URL: "default_value"
  PIPELINE_ID: "default_value"
  STATUS: "default_value"
  VERSION: "${CI_COMMIT_BRANCH#release/}"
  GIT_STRATEGY: clone
# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  key: "$CI_JOB_NAME"

stages:
  - Compilation
  - Conflict check
  - Test
  - Quality
  - Packaging
  - Deployment
  - Manual versioning
  - Auto versioning
  - Notify

#==== Jobs related to compilation stage
#Compile:
#  stage: Compilation
#  image: node:23-alpine3.20
#  allow_failure: false
#  rules:
#    # Rule 1: Run on specific branches if commit message is not "chore: generate changelog.md file"
#    - if: >
#        ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ /^release\/.*$/ || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG) &&
#        $CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/
#    # Rule 2: Run on merge requests to dev, main, or master
#    - if: >
#        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" ||
#         $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
#         $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master") &&
#         $CI_PIPELINE_SOURCE == "merge_request_event"
#  before_script:
#    - apk update update
#    - npm install --force
#    - npm cache clean --force
#    - npm install -g @angular/cli
#  script:
#    - ng build

#==== Jobs related to conflict check stage
#Verify merge conflicts:
#  stage: Conflict check
#  allow_failure: false
#  rules:
#    - if: '($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main") && $CI_PIPELINE_SOURCE == "merge_request_event"'
#  before_script:
#    - apk update
#    - apk add --no-cache git
#    - echo "JOB_NAME=$CI_JOB_NAME" > notified_job.env
#    - echo "JOB_URL=$CI_JOB_URL" >> notified_job.env
#    - echo "PIPELINE_ID=$CI_JOB_ID" >> notified_job.env
#    - echo "STATUS=failed" >> notified_job.env
#  script:
#    - 'git config --global user.email "hamza.habchi@messaging-technologies.com"'
#    - 'git config --global user.name "hamza.habchi"'
#    - 'git config pull.rebase false'
#    - 'git fetch --all'
#    - 'git config --local -l'
#    - 'git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
#    - 'git pull origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
#    - 'git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
#    - 'git pull origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
#    - 'git merge $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
#    - sed -i -e 's/STATUS=.*/STATUS=success/g' notified_job.env
#  artifacts:
#    reports:
#      dotenv: notified_job.env

#Verify version integrity:
#  stage: Conflict check
#  image: node:23-alpine3.20
#  allow_failure: false
#  variables:
#    GIT_STRATEGY: clone
#  rules:
#    - if: '$CI_COMMIT_BRANCH =~ /^release\/.*$/ && $CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
#  before_script:
#    - apk update
#    - apk add --no-cache git
#    - echo "JOB_NAME=$CI_JOB_NAME" > notified_job.env
#    - echo "JOB_URL=$CI_JOB_URL" >> notified_job.env
#    - echo "PIPELINE_ID=$CI_JOB_ID" >> notified_job.env
#    - echo "STATUS=failed" >> notified_job.env
#  script:
#    - echo "Starting script execution"
#    - VERSION="${CI_COMMIT_BRANCH#release/}"
#    - 'echo "Extracted version from branch: $VERSION"'

    # Validate version format
#    - |
#      if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(-(RELEASE|RC[0-9]*|SNAPSHOT))?$'; then
#        echo "❌ Invalid version format in branch: $VERSION. Version should be in format number X.Y.Z and can be followed by either -SNAPSHOT, -RELEASE, -RC with or without numbers (RC1, RC2 ...)";
#        exit 1;
#      fi

    # Ensure package.json
#    - if [ ! -f "package.json" ]; then echo "❌ package.json not found!"; exit 1; fi
#
#    # Check version consistency
#    - PACKAGE_VERSION=$(node -pe "require('./package.json').version")
#    - 'echo "Version from package.json: $PACKAGE_VERSION"'
#    - |
#      if [ "$VERSION" != "$PACKAGE_VERSION" ]; then
#        echo "❌ Version mismatch: Branch version ($VERSION) does not match package.json version ($PACKAGE_VERSION)";
#        exit 1;
#      fi
#
#    - echo "✅ Version integrity check passed!"

#==== Jobs related to Test stage
#Unit Test:
#  stage: Test
#  allow_failure: false
#  rules:
#    # Rule 1: Run on specific branches if commit message is not "chore: generate changelog.md file"
#    - if: '$CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
#  before_script:
#    - apk update
#    - npm install --force
#    - apk add --no-cache git
#    - echo "JOB_NAME=$CI_JOB_NAME" > notified_job.env
#    - echo "JOB_URL=$CI_JOB_URL" >> notified_job.env
#    - echo "PIPELINE_ID=$CI_JOB_ID" >> notified_job.env
#    - echo "STATUS=failed" >> notified_job.env
#  script:
#    # Ensure dependencies are installed
#    - npm ci --force
#    # Run Angular unit tests with coverage
#    # Run tests with more verbose output to capture detailed logs
#    - npm run test --watch --browsers=ChromeHeadless
#    # Check if coverage folder exists and contains files
#    - ls -la  coverage/  # This will show the contents of the coverage directory
#    - echo "Coverage folder contents:"
#    - ls -la coverage/  # Output the contents for debugging
#
#    # Check for coverage folder and update status accordingly
#    - |
#      if [ -d "coverage" ] && [ "$(ls -A coverage)" ]; then
#        echo "Coverage folder found and not empty. Proceeding to success status."
#        sed -i -e 's/STATUS=.*/STATUS=success/g' notified_job.env
#      else
#        echo "Coverage folder not found or empty. Keeping status as failed."
#      fi
#  artifacts:
#    reports:
#      dotenv: notified_job.env
#    paths:
#      - coverage/  # Ensure the coverage folder is stored as an artifact

#==== Jobs related to Quality stage
#Sonar Analysis:
#  stage: Quality
#  allow_failure: false
#  needs:
#    - Unit Test
#  rules:
#    # Rule 1: Run on specific branches if commit message is not "chore: generate changelog.md file"
#    - if: '$CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
#  before_script:
#    - apk update && apk add --no-cache git curl
#    - echo "JOB_NAME=$CI_JOB_NAME" > notified_job.env
#    - echo "JOB_URL=$CI_JOB_URL" >> notified_job.env
#    - echo "PIPELINE_ID=$CI_PIPELINE_ID" >> notified_job.env
#    - echo "STATUS=failed" >> notified_job.env
#    # Ensure sonar-scanner is available
#    - npm install -g @sonar/scan --force
#  script:
#    - echo "Determining SonarQube environment..."
#    - echo "$CI_COMMIT_REF_NAME"
#    - |
#      if [[ -n "$CI_COMMIT_TAG" ]]; then
#        SONAR_TOKEN="$SONAR_PROD_TOKEN"
#        SONAR_URL="$SONAR_PROD_URL"
#        echo "Running SonarQube analysis in PRODUCTION mode. Token: $SONAR_TOKEN and Host: $SONAR_URL"
#      else
#        SONAR_TOKEN="$SONAR_QA_TOKEN"
#        SONAR_URL="$SONAR_QA_URL"
#        echo "Running SonarQube analysis in QA mode. Token: $SONAR_TOKEN and Host: $SONAR_URL"
#      fi
#
#      # Create sonar-project.properties file
#      cat <<EOF > sonar-project.properties
#      sonar.projectKey=$SONAR_PROJECT_KEY
#      sonar.host.url=$SONAR_URL
#      sonar.token=$SONAR_TOKEN
#
#      # Source and coverage configuration
#      sonar.sources=src/app
#      sonar.javascript.lcov.reportPaths=coverage/lcov.info
#
#      # Exclusions
#      sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/routes.ts, **/app.routes.ts,**/dashboard/**,**/src/components/**,**/*.css,**/*.scss,**/*.html
#      EOF
#
#      echo "sonar-project.properties file has been created."
#
#    # Run SonarQube analysis
#    - sonar
#
#    - sed -i -e 's/STATUS=.*/STATUS=success/g' notified_job.env
#
#  artifacts:
#    reports:
#      dotenv: notified_job.env
#    paths:
#      - coverage/

#Quality Gate:
#  stage: Quality
#  allow_failure: false
#  needs:
#    - Sonar Analysis
#  rules:
#    # Rule 1: Run on specific branches if commit message is not "chore: generate changelog.md file"
#    - if: '$CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
#  before_script:
#    - apk update && apk add --no-cache curl jq
#    - echo "JOB_NAME=$CI_JOB_NAME" > notified_job.env
#    - echo "JOB_URL=$CI_JOB_URL" >> notified_job.env
#    - echo "PIPELINE_ID=$CI_PIPELINE_ID" >> notified_job.env
#    - echo "STATUS=failed" >> notified_job.env
#  script:
#    - echo "Determining SonarQube environment..."
#    - |
#      if [[ -n "$CI_COMMIT_TAG" ]]; then
#        SONAR_TOKEN="$SONAR_PROD_TOKEN"
#        SONAR_URL="$SONAR_PROD_URL"
#        echo "Running SonarQube analysis in PRODUCTION mode."
#      else
#        SONAR_TOKEN="$SONAR_QA_TOKEN"
#        SONAR_URL="$SONAR_QA_URL"
#        echo "Running SonarQube analysis in QA mode."
#      fi
#    - echo "Checking quality gate for project $SONAR_PROJECT_KEY..."
#    - |
#      STATUS=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" | jq -r '.projectStatus.status')
#      echo "SonarQube Quality Gate status: $STATUS"
#      if [ "$STATUS" != "OK" ]; then
#        echo "Quality Gate failed!"
#        exit 1
#      else
#        echo "✅ Quality Gate passed."
#      fi
#    - sed -i -e 's/STATUS=.*/STATUS=success/g' notified_job.env
#  artifacts:
#    reports:
#      dotenv: notified_job.env

#==== Jobs related to packaging stage
Docker image build & push:
  stage: Packaging
  allow_failure: false
  rules:
    - if: '($CI_COMMIT_BRANCH =~ /^release\/.*/ || $CI_COMMIT_REF_NAME == "dev" || $CI_COMMIT_TAG) && $CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
  image: docker:latest
  script:
    - ls -lh
    - chmod +x .gitlab/push-docker-image.sh
    - docker login -u "$REGISTRY_USER" --password-stdin "$REGISTRY_URL"
    - apk update && apk add --no-cache nodejs
    - ./.gitlab/push-docker-image.sh $REGISTRY_URL

#==== Jobs related to Deployment stage
#Deploy to QA:
#  stage: Deployment
#  allow_failure: false
#  image: arvindr226/alpine-ssh
#  rules:
#    - if: '($CI_COMMIT_BRANCH =~ /^release\/.*/ || $CI_COMMIT_REF_NAME == "dev" || $CI_COMMIT_TAG) && $CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
#  before_script:
#    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#    - eval $(ssh-agent -s)
#    - echo "$ALTERWAY_PEM" | tr -d '\r' | ssh-add - > /dev/null
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#  script:
#    - echo "Deploying to server..."
#    - ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null smsdevdocker01@51.159.142.28 -p 2222 'docker compose -f /opt/smsmode-docker-compose/microservices/admin-ui/docker-compose.yml down; docker image rm docker-snapshots.smsmode.fr/messaging-technologies/admin-ui; docker compose -f /opt/smsmode-docker-compose/microservices/admin-ui/docker-compose.yml up -d'
#
#Deploy to Stage:
#  stage: Deployment
#  allow_failure: false
#  rules:
#    - if: '($CI_COMMIT_BRANCH =~ /^release\/.*/ || $CI_COMMIT_TAG) && $CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
#  before_script:
#    - echo "JOB_NAME=$CI_JOB_NAME" > notified_job.env
#    - echo "JOB_URL=$CI_JOB_URL" >> notified_job.env
#    - echo "PIPELINE_ID=$CI_JOB_ID" >> notified_job.env
#    - echo "STATUS=failed" >> notified_job.env
#    - which ssh-agent || ( apk update && apk add --no-cache openssh-client )
#    - eval $(ssh-agent -s)
#    - echo "$ALTERWAY_PEM" | tr -d '\r' | ssh-add - > /dev/null
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#  script:
#    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 51.159.142.28 -p 2222 -l smsrctdocker01 'docker compose -f /opt/smsmode-docker-compose/microservices/admin-ui/docker-compose.yml down; docker image rm docker-snapshots.smsmode.fr/messaging-technologies/admin-ui; docker compose -f /opt/smsmode-docker-compose/microservices/admin-ui/docker-compose.yml up -d'
#
##==== Jobs related to Manual versioning stage
#Generate changelog:
#  stage: Manual versioning
#  allow_failure: false
#  image: arvindr226/alpine-ssh
#  rules:
#    - if: '$CI_COMMIT_BRANCH =~ /^release\/.*$/ && $CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
#  variables:
#    GIT_STRATEGY: clone
#  before_script:
#    - apk update
#    - apk add --no-cache git
#    - apk add --no-cache curl
#    - apk add --no-cache gawk
#    - apk add --no-cache jq
#    - git config --global user.email "hamza.habchi@messaging-technologies.com"
#    - git config --global user.name "Hamza HABCHI"
#    - git checkout "$CI_COMMIT_REF_NAME"
#    - echo "$CI_COMMIT_REF_NAME"
#    - git status
#  script:
#    - git branch -v
#    - VERSION="${CI_COMMIT_BRANCH#release/}"  # Extract version from branch name
#    - chmod +x .gitlab/changelog-script.sh
#    - 'echo "Extracted version: $VERSION"'
#    - ls .gitlab
#    - ./.gitlab/changelog-script.sh "$JIRA_PROJECT_KEY" "$ATLASSIAN_TOKEN" "$VERSION" "$JIRA_API_URL"
#    - git add changelog.md
#    - |
#      if [[ -n $(git status --porcelain) ]]; then
#        git commit -am "chore: generate changelog.md file"
#        git remote set-url origin "https://oauth2:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
#        git push origin HEAD:$CI_COMMIT_REF_NAME
#      else
#        echo "No changes detected. Skipping commit."
#      fi
#
#Generate release note:
#  stage: Manual versioning
#  allow_failure: true
#  image: arvindr226/alpine-ssh
#  rules:
#    - if: '$CI_COMMIT_BRANCH =~ /^release\/.*$/ && $CI_COMMIT_BRANCH !~ /-RELEASE$/ && $CI_COMMIT_MESSAGE !~ /chore: generate changelog.md file/'
#  when: manual
#  variables:
#    GIT_STRATEGY: clone
#  before_script:
#    - 'echo "Installing dependencies ..."'
#    - apk add --no-cache jq
#    - 'echo "✅ jq installed"'
#    - apk add --no-cache curl
#    - 'echo "✅ curl installed"'
#  script:
#    - VERSION="${CI_COMMIT_BRANCH#release/}"  # Extract version from branch name
#    - chmod +x .gitlab/release-note-script.sh
#    - ls -la .gitlab/
#    - 'echo "Extracted version: $VERSION"'
#    - ./.gitlab/release-note-script.sh "$JIRA_PROJECT_KEY" "$ATLASSIAN_TOKEN" "$VERSION" "$CONFLUENCE_API_URL" "$SPACE_KEY" "$CONFLUENCE_RELEASE_PAGE_ID"
#
##==== Jobs related to Auto Versioning stage
#Release note generation:
#  stage: Auto versioning
#  allow_failure: false
#  only:
#    - tags
#  variables:
#    GIT_STRATEGY: clone
#  before_script:
#    - 'echo "Installing dependencies ..."'
#    - apk add --no-cache jq
#    - 'echo "✅ jq installed"'
#    - apk add --no-cache curl
#    - 'echo "✅ curl installed"'
#    - apk add --no-cache git xmlstarlet
#    - 'echo "✅ git, xmlstarlet installed"'
#  script:
#      # Ensure package.json
#    - if [ ! -f "package.json" ]; then echo "❌ package.json not found!"; exit 1; fi
#    - VERSION=$(node -pe "require('./package.json').version")
#    - 'echo "Version from package.json: $VERSION"'
#    - chmod +x .gitlab/release-note-script.sh
#    - ls -la .gitlab/
#    - ./.gitlab/release-note-script.sh "$JIRA_PROJECT_KEY" "$ATLASSIAN_TOKEN" "$VERSION" "$CONFLUENCE_API_URL" "$SPACE_KEY" "$CONFLUENCE_RELEASE_PAGE_ID"
