export enum RoomSubTypeEnum{
  LIVING_ROOM='LIVING_ROOM',
  BED_IN_LIVING_ROOM='BED_IN_LIVING_ROOM',
  MASTER='MASTER',
  CHILDREN='CHILDREN',
  GUEST='GUEST',
  FULL='FULL',
  HALF='HALF',
  THREE_QUARTER='THREE_QUARTER',
  QUARTER='QUARTER',
  KITCHENETTE='KITCHENETTE',
}
