export enum RoomTypeEnum {
  BEDROOM = 'BEDROOM',
  GUEST_BEDROOM = 'GUEST_BEDROOM',
  KID_BEDROOM = 'KID_BEDROOM',
  MASTER_BEDROOM = 'MASTER_BEDROOM',
  LIVING_ROOM = 'LIVING_ROOM',
  KITCHEN = 'KITCHEN',
  FULL_BATHROOM = 'FULL_BATHROOM',
  HALF_BATHROOM = 'HALF_BATHROOM'
}
